import { CATEGORIES, productHref } from "@/lib/content";

export interface NavItem {
  label: string;
  href: string;
}

export interface NavLink extends NavItem {
  dropdown?: NavItem[];
}

/**
 * The site navigation, generated from the product taxonomy in content.ts.
 *
 * It used to be a hand-typed list, which is how every "Bags by Industry" link
 * and both "Cardboard Boxes" links ended up pointing at slugs that do not
 * exist. Deriving it means a dropdown entry can only ever point at a page that
 * is actually generated by generateStaticParams.
 */
export const navLinks: NavLink[] = [
  { label: "Home", href: "/" },
  { label: "About Us", href: "/about" },
  ...CATEGORIES.map((category) => ({
    label: category.label,
    href: `/${category.slug}`,
    dropdown: category.items.map((item) => ({
      label: item.name,
      href: productHref(item),
    })),
  })),
  {
    label: "Our Clients",
    href: "/clients",
    dropdown: [{ label: "Contact Us", href: "/clients/contact-us" }],
  },
  { label: "Blogs", href: "/blogs" },
];

/** Where every "get a quote"-style link should land. */
export const CONTACT_HREF = "/clients/contact-us";
